https://bugs.launchpad.net/py3dns/+bug/1319611

--- DNS/Lib.py
+++ DNS/Lib.py
@@ -36,6 +36,11 @@
 
 from .Base import DNSError
 
+try:
+    import ipaddress
+except ImportError:
+    import ipaddr as ipaddress
+
 LABEL_UTF8 = False
 LABEL_ENCODING = 'idna'
 
@@ -518,7 +523,6 @@
         RRunpacker.__init__(self, buf)
         self.rdend = None
     def getAdata(self):
-        import ipaddress
         if DNS.LABEL_UTF8:
             enc = 'utf8'
         else:
@@ -526,7 +530,6 @@
         x = socket.inet_aton(self.getaddr().decode(enc))
         return ipaddress.IPv4Address(struct_unpack("!I", x)[0])
     def getAAAAdata(self):
-        import ipaddress
         return ipaddress.IPv6Address(bin2addr6(self.getaddr6()))
 
 class RRunpackerText(RRunpackerDefault):
--- DNS/tests/test_base.py
+++ DNS/tests/test_base.py
@@ -3,7 +3,10 @@
 
 import DNS
 import unittest
-import ipaddress
+try:
+    import ipaddress
+except ImportError:
+    import ipaddr as ipaddress
 
 def assertIsByte(b):
     assert b >= 0
@@ -54,7 +57,6 @@
 
 
     def testDnsRequestAAAA(self):
-        import ipaddress
         dnsobj = DNS.DnsRequest('example.org')
         
         aaaa_response = dnsobj.qry(qtype='AAAA', resulttype='text')
